"""Contract tests for locked dependency audit evidence."""

from __future__ import annotations

import json
import os
import sys
from collections.abc import Callable, Mapping, Sequence
from datetime import datetime, timezone
from pathlib import Path
from subprocess import CalledProcessError, CompletedProcess, TimeoutExpired
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = REPO_ROOT / "scripts"
SCRIPT_PATH = SCRIPTS_DIR / "verify_dependency_audit.py"
sys.path.insert(0, str(SCRIPTS_DIR))

import verify_dependency_audit as verifier  # noqa: E402

CORE_REQUIREMENTS = (
    f"# generated by the fake uv export\nalpha==1.0 \\\n    --hash=sha256:{'a' * 64}\n"
)
TUI_REQUIREMENTS = CORE_REQUIREMENTS + "beta==2.0 \\\n" + f"    --hash=sha256:{'b' * 64}\n"
CORE_AUDIT = {
    "dependencies": [{"name": "alpha", "version": "1.0", "vulns": []}],
    "fixes": [],
}
TUI_AUDIT = {
    "dependencies": [
        {"name": "alpha", "version": "1.0", "vulns": []},
        {"name": "beta", "version": "2.0", "vulns": []},
    ],
    "fixes": [],
}
FIXED_TIME = datetime(2026, 7, 15, 12, 34, 56, 123456, tzinfo=timezone.utc)  # noqa: UP017


class RecordingRunner:
    """Write deterministic fake outputs while recording the subprocess boundary."""

    def __init__(
        self,
        *,
        fail_at: int | None = None,
        fail_with_return: bool = False,
        mutate_output: Callable[[int, Path], None] | None = None,
        after_call: Callable[[int], None] | None = None,
    ) -> None:
        self.fail_at = fail_at
        self.fail_with_return = fail_with_return
        self.mutate_output = mutate_output
        self.after_call = after_call
        self.calls: list[dict[str, Any]] = []

    def __call__(
        self,
        args: Sequence[object],
        *,
        cwd: Path,
        env: Mapping[str, str],
        check: bool,
        capture_output: bool,
        text: bool,
        timeout: float,
        shell: bool,
    ) -> CompletedProcess[str]:
        command = [str(part) for part in args]
        call_index = len(self.calls)
        self.calls.append(
            {
                "args": command,
                "cwd": Path(cwd),
                "env": dict(env),
                "check": check,
                "capture_output": capture_output,
                "text": text,
                "timeout": timeout,
                "shell": shell,
            }
        )
        if call_index == self.fail_at:
            if self.fail_with_return:
                return CompletedProcess(
                    command,
                    7,
                    "hostile-return-stdout\n",
                    "hostile-return-stderr\n",
                )
            raise CalledProcessError(
                7,
                ["secret-command", "--token", "do-not-render"],
                output="hostile-failure-stdout\n",
                stderr="hostile-failure-stderr\n",
            )

        output_path = Path(command[-1])
        if call_index == 0:
            output_path.write_text(CORE_REQUIREMENTS, encoding="utf-8")
        elif call_index == 1:
            output_path.write_text(TUI_REQUIREMENTS, encoding="utf-8")
        elif call_index == 2:
            output_path.write_text(json.dumps(CORE_AUDIT), encoding="utf-8")
        elif call_index == 3:
            output_path.write_text(json.dumps(TUI_AUDIT), encoding="utf-8")
        else:
            raise AssertionError(f"unexpected fake command: {command}")
        if self.mutate_output is not None:
            self.mutate_output(call_index, output_path)
        if self.after_call is not None:
            self.after_call(call_index)
        return CompletedProcess(
            command,
            0,
            f"raw-stdout-{call_index}\n",
            f"raw-stderr-{call_index}\n",
        )


def _fixed_now() -> datetime:
    return FIXED_TIME


def _verify(tmp_path: Path, runner: RecordingRunner) -> tuple[tuple[Path, Path], Path]:
    evidence_dir = tmp_path / "dependency-audit"
    result_paths = verifier.verify_dependency_audit(
        evidence_dir,
        run_command=runner,
        now=_fixed_now,
    )
    return result_paths, evidence_dir.resolve()


def test_dependency_audit_verifier_exists() -> None:
    assert SCRIPT_PATH.is_file()


def test_build_commands_uses_exact_locked_core_and_tui_contract(tmp_path: Path) -> None:
    evidence_dir = tmp_path / "dependency-audit"
    core_path = evidence_dir / "core-requirements.txt"
    tui_path = evidence_dir / "tui-requirements.txt"
    core_output = evidence_dir / "core-pip-audit.json"
    tui_output = evidence_dir / "tui-pip-audit.json"

    assert verifier.build_commands(evidence_dir) == (
        (
            "uv",
            "export",
            "--frozen",
            "--no-dev",
            "--no-emit-project",
            "--format",
            "requirements.txt",
            "--output-file",
            str(core_path),
        ),
        (
            "uv",
            "export",
            "--frozen",
            "--no-dev",
            "--no-emit-project",
            "--extra",
            "tui",
            "--format",
            "requirements.txt",
            "--output-file",
            str(tui_path),
        ),
        (
            "uvx",
            "--from",
            "pip-audit==2.10.1",
            "pip-audit",
            "--requirement",
            str(core_path),
            "--no-deps",
            "--disable-pip",
            "--format",
            "json",
            "--output",
            str(core_output),
        ),
        (
            "uvx",
            "--from",
            "pip-audit==2.10.1",
            "pip-audit",
            "--requirement",
            str(tui_path),
            "--no-deps",
            "--disable-pip",
            "--format",
            "json",
            "--output",
            str(tui_output),
        ),
    )


def test_success_writes_validated_manifest_and_combined_raw_log(tmp_path: Path) -> None:
    runner = RecordingRunner()

    result_paths, evidence_dir = _verify(tmp_path, runner)

    assert result_paths == (
        evidence_dir / "core-pip-audit.json",
        evidence_dir / "tui-pip-audit.json",
    )
    assert json.loads((evidence_dir / "manifest.json").read_text(encoding="utf-8")) == {
        "audit_tool": "pip-audit==2.10.1",
        "observed_at": "2026-07-15T12:34:56.123456+00:00",
        "paths": {
            "core": {
                "requirements": "core-requirements.txt",
                "result": "core-pip-audit.json",
            },
            "tui": {
                "requirements": "tui-requirements.txt",
                "result": "tui-pip-audit.json",
            },
        },
    }
    combined_log = (evidence_dir / "pip-audit.log").read_text(encoding="utf-8")
    for call_index in range(4):
        assert f"raw-stdout-{call_index}\n" in combined_log
        assert f"raw-stderr-{call_index}\n" in combined_log
    assert not tuple(evidence_dir.glob(".*.tmp"))


def test_every_command_is_bounded_checked_sanitized_and_runs_at_repo_root(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("PIP_INDEX_URL", "https://token@hostile.invalid/simple")
    monkeypatch.setenv("UV_INDEX_URL", "https://token@hostile.invalid/simple")
    monkeypatch.setenv("PYTHONPATH", "/hostile/source")
    monkeypatch.setenv("VIRTUAL_ENV", "/hostile/venv")
    runner = RecordingRunner()

    _verify(tmp_path, runner)

    assert len(runner.calls) == 4
    for call in runner.calls:
        assert isinstance(call["args"], list)
        assert call["cwd"] == REPO_ROOT
        assert call["check"] is True
        assert call["capture_output"] is True
        assert call["text"] is True
        assert call["timeout"] == verifier.COMMAND_TIMEOUT_SECONDS
        assert call["shell"] is False
        environment = call["env"]
        assert "PIP_INDEX_URL" not in environment
        assert "UV_INDEX_URL" not in environment
        assert "PYTHONPATH" not in environment
        assert "VIRTUAL_ENV" not in environment
        assert environment["PIP_CONFIG_FILE"] == os.devnull
        assert environment["PIP_NO_INPUT"] == "1"
        assert environment["PYTHONNOUSERSITE"] == "1"
        assert environment["UV_NO_CONFIG"] == "1"


@pytest.mark.parametrize("fail_at", range(4))
def test_each_command_failure_stops_later_commands_and_cannot_emit_success(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
    fail_at: int,
) -> None:
    runner = RecordingRunner(fail_at=fail_at)
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(SystemExit) as excinfo:
        verifier.main(
            ["--evidence-dir", str(evidence_dir)],
            run_command=runner,
            now=_fixed_now,
        )

    captured = capsys.readouterr()
    assert excinfo.value.code == 2
    assert captured.out == ""
    assert len(runner.calls) == fail_at + 1
    assert not (evidence_dir / "manifest.json").exists()
    failure_log = (evidence_dir / "pip-audit.log").read_text(encoding="utf-8")
    assert "hostile-failure-stdout\n" in failure_log
    assert "hostile-failure-stderr\n" in failure_log
    assert "do-not-render" not in captured.err
    assert "hostile-failure" not in captured.err


def test_nonzero_return_is_fail_closed_even_when_runner_does_not_raise(tmp_path: Path) -> None:
    runner = RecordingRunner(fail_at=2, fail_with_return=True)
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match="exit status 7"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert len(runner.calls) == 3
    assert not (evidence_dir / "manifest.json").exists()
    failure_log = (evidence_dir / "pip-audit.log").read_text(encoding="utf-8")
    assert "hostile-return-stdout\n" in failure_log
    assert "hostile-return-stderr\n" in failure_log


def test_timeout_is_redacted_but_preserved_in_failure_log(tmp_path: Path) -> None:
    class TimeoutRunner(RecordingRunner):
        def __call__(self, *args: object, **kwargs: object) -> CompletedProcess[str]:
            if len(self.calls) == 2:
                self.calls.append({"args": list(args)})
                raise TimeoutExpired(
                    ["secret-command", "--token", "do-not-render"],
                    1,
                    output=b"timeout-secret-stdout\n",
                    stderr=b"timeout-secret-stderr\n",
                )
            return super().__call__(*args, **kwargs)

    runner = TimeoutRunner()
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError) as excinfo:
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert "timed out" in str(excinfo.value)
    assert "do-not-render" not in str(excinfo.value)
    assert "timeout-secret" not in str(excinfo.value)
    failure_log = (evidence_dir / "pip-audit.log").read_text(encoding="utf-8")
    assert "timeout-secret-stdout\n" in failure_log
    assert "timeout-secret-stderr\n" in failure_log
    assert not (evidence_dir / "manifest.json").exists()


def test_cli_prints_only_both_result_paths_after_complete_success(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    runner = RecordingRunner()
    evidence_dir = tmp_path / "dependency-audit"

    assert (
        verifier.main(
            ["--evidence-dir", str(evidence_dir)],
            run_command=runner,
            now=_fixed_now,
        )
        == 0
    )

    assert capsys.readouterr().out.splitlines() == [
        str(evidence_dir.resolve() / "core-pip-audit.json"),
        str(evidence_dir.resolve() / "tui-pip-audit.json"),
    ]


def test_existing_evidence_directory_is_rejected_before_any_command(tmp_path: Path) -> None:
    evidence_dir = tmp_path / "dependency-audit"
    evidence_dir.mkdir()
    runner = RecordingRunner()

    with pytest.raises(verifier.DependencyAuditError, match="must not already exist"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert runner.calls == []


def test_existing_file_at_evidence_path_is_rejected_before_any_command(tmp_path: Path) -> None:
    evidence_dir = tmp_path / "dependency-audit"
    evidence_dir.write_text("foreign", encoding="utf-8")
    runner = RecordingRunner()

    with pytest.raises(verifier.DependencyAuditError, match="must not already exist"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert runner.calls == []


def test_evidence_directory_symlink_is_rejected_before_any_command(tmp_path: Path) -> None:
    target = tmp_path / "target"
    target.mkdir()
    evidence_dir = tmp_path / "dependency-audit"
    evidence_dir.symlink_to(target, target_is_directory=True)
    runner = RecordingRunner()

    with pytest.raises(verifier.DependencyAuditError, match="must not be a symlink"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert runner.calls == []


def test_evidence_parent_symlink_is_rejected_before_any_command(tmp_path: Path) -> None:
    target = tmp_path / "target"
    target.mkdir()
    linked_parent = tmp_path / "linked-parent"
    linked_parent.symlink_to(target, target_is_directory=True)
    runner = RecordingRunner()

    with pytest.raises(verifier.DependencyAuditError, match="parent must not be a symlink"):
        verifier.verify_dependency_audit(
            linked_parent / "dependency-audit",
            run_command=runner,
            now=_fixed_now,
        )

    assert runner.calls == []


def test_missing_parent_directories_are_created_exclusively(tmp_path: Path) -> None:
    runner = RecordingRunner()
    evidence_dir = tmp_path / "new" / "nested" / "dependency-audit"

    verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert evidence_dir.is_dir()


@pytest.mark.parametrize("output_index", range(4))
def test_every_generated_output_must_be_a_regular_non_symlink_file(
    tmp_path: Path, output_index: int
) -> None:
    external = tmp_path / f"external-{output_index}"
    external.write_text("foreign", encoding="utf-8")

    def replace_with_symlink(call_index: int, output_path: Path) -> None:
        if call_index == output_index:
            output_path.unlink()
            output_path.symlink_to(external)

    runner = RecordingRunner(mutate_output=replace_with_symlink)
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match="regular non-symlink file"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert len(runner.calls) == output_index + 1
    assert not (evidence_dir / "manifest.json").exists()


@pytest.mark.parametrize("output_index", range(4))
def test_every_generated_output_must_be_nonempty(tmp_path: Path, output_index: int) -> None:
    def empty_output(call_index: int, output_path: Path) -> None:
        if call_index == output_index:
            output_path.write_bytes(b"")

    runner = RecordingRunner(mutate_output=empty_output)
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match="must not be empty"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert len(runner.calls) == output_index + 1
    assert not (evidence_dir / "manifest.json").exists()


@pytest.mark.parametrize("output_index", [0, 1])
def test_each_requirement_export_must_be_hash_locked(tmp_path: Path, output_index: int) -> None:
    def remove_hash(call_index: int, output_path: Path) -> None:
        if call_index == output_index:
            output_path.write_text("alpha==1.0\n", encoding="utf-8")

    runner = RecordingRunner(mutate_output=remove_hash)
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match="hash-locked"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert len(runner.calls) == output_index + 1
    assert not (evidence_dir / "manifest.json").exists()


@pytest.mark.parametrize("output_index", [2, 3])
def test_each_audit_output_must_be_valid_json(tmp_path: Path, output_index: int) -> None:
    def corrupt_json(call_index: int, output_path: Path) -> None:
        if call_index == output_index:
            output_path.write_text("not-json", encoding="utf-8")

    runner = RecordingRunner(mutate_output=corrupt_json)
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match="valid JSON"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert len(runner.calls) == output_index + 1
    assert not (evidence_dir / "manifest.json").exists()


@pytest.mark.parametrize("output_index", [2, 3])
def test_each_audit_output_must_report_no_vulnerabilities(
    tmp_path: Path, output_index: int
) -> None:
    def add_vulnerability(call_index: int, output_path: Path) -> None:
        if call_index == output_index:
            payload = CORE_AUDIT if output_index == 2 else TUI_AUDIT
            vulnerable = json.loads(json.dumps(payload))
            vulnerable["dependencies"][0]["vulns"] = [{"id": "GHSA-test"}]
            output_path.write_text(json.dumps(vulnerable), encoding="utf-8")

    runner = RecordingRunner(mutate_output=add_vulnerability)
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match="reported vulnerabilities"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert len(runner.calls) == output_index + 1
    assert not (evidence_dir / "manifest.json").exists()


def test_audit_dependency_set_must_match_the_hashed_requirements(tmp_path: Path) -> None:
    def omit_dependency(call_index: int, output_path: Path) -> None:
        if call_index == 3:
            output_path.write_text(json.dumps(CORE_AUDIT), encoding="utf-8")

    runner = RecordingRunner(mutate_output=omit_dependency)
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match="dependency set did not match"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert not (evidence_dir / "manifest.json").exists()


def test_earlier_output_mutation_is_detected_before_manifest(tmp_path: Path) -> None:
    evidence_dir = tmp_path / "dependency-audit"

    def mutate_core_after_final_command(call_index: int) -> None:
        if call_index == 3:
            (evidence_dir / "core-requirements.txt").write_text(
                "alpha==9.9 \\\n" + f"    --hash=sha256:{'9' * 64}\n",
                encoding="utf-8",
            )

    runner = RecordingRunner(after_call=mutate_core_after_final_command)

    with pytest.raises(verifier.DependencyAuditError, match="changed after validation"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert not (evidence_dir / "manifest.json").exists()


def test_foreign_manifest_cannot_be_replaced_with_success_evidence(tmp_path: Path) -> None:
    evidence_dir = tmp_path / "dependency-audit"

    def create_foreign_manifest(call_index: int) -> None:
        if call_index == 3:
            (evidence_dir / "manifest.json").write_text("foreign", encoding="utf-8")

    runner = RecordingRunner(after_call=create_foreign_manifest)

    with pytest.raises(verifier.DependencyAuditError, match="manifest already exists"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert (evidence_dir / "manifest.json").read_text(encoding="utf-8") == "foreign"


def test_missing_frozen_lock_is_rejected_before_any_command(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    fake_repo = tmp_path / "repo"
    fake_repo.mkdir()
    monkeypatch.setattr(verifier, "REPO_ROOT", fake_repo)
    runner = RecordingRunner()

    with pytest.raises(verifier.DependencyAuditError, match=r"uv\.lock"):
        verifier.verify_dependency_audit(
            tmp_path / "dependency-audit",
            run_command=runner,
            now=_fixed_now,
        )

    assert runner.calls == []
