"""Contract tests for locked dependency audit evidence."""

from __future__ import annotations

import hashlib
import json
import os
import sys
from collections.abc import Callable, Mapping, Sequence
from datetime import datetime, timezone
from pathlib import Path
from subprocess import CalledProcessError, CompletedProcess, TimeoutExpired
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = REPO_ROOT / "scripts"
SCRIPT_PATH = SCRIPTS_DIR / "verify_dependency_audit.py"
sys.path.insert(0, str(SCRIPTS_DIR))

import verify_dependency_audit as verifier  # noqa: E402

CORE_REQUIREMENTS = (
    f"# generated by the fake uv export\nalpha==1.0 \\\n    --hash=sha256:{'a' * 64}\n"
)
TUI_REQUIREMENTS = CORE_REQUIREMENTS + "beta==2.0 \\\n" + f"    --hash=sha256:{'b' * 64}\n"
CORE_AUDIT = {
    "dependencies": [{"name": "alpha", "version": "1.0", "vulns": []}],
    "fixes": [],
}
TUI_AUDIT = {
    "dependencies": [
        {"name": "alpha", "version": "1.0", "vulns": []},
        {"name": "beta", "version": "2.0", "vulns": []},
    ],
    "fixes": [],
}
FIXED_TIME = datetime(2026, 7, 15, 12, 34, 56, 123456, tzinfo=timezone.utc)  # noqa: UP017


def _hashed_requirement(requirement: str, hash_character: str = "c") -> str:
    return f"{requirement} \\\n    --hash=sha256:{hash_character * 64}\n"


class RecordingRunner:
    """Write deterministic fake outputs while recording the subprocess boundary."""

    def __init__(
        self,
        *,
        fail_at: int | None = None,
        fail_with_return: bool = False,
        mutate_output: Callable[[int, Path], None] | None = None,
        after_call: Callable[[int], None] | None = None,
    ) -> None:
        self.fail_at = fail_at
        self.fail_with_return = fail_with_return
        self.mutate_output = mutate_output
        self.after_call = after_call
        self.calls: list[dict[str, Any]] = []

    def __call__(
        self,
        args: Sequence[object],
        *,
        cwd: Path,
        env: Mapping[str, str],
        check: bool,
        capture_output: bool,
        text: bool,
        timeout: float,
        shell: bool,
    ) -> CompletedProcess[str]:
        command = [str(part) for part in args]
        call_index = len(self.calls)
        self.calls.append(
            {
                "args": command,
                "cwd": Path(cwd),
                "env": dict(env),
                "check": check,
                "capture_output": capture_output,
                "text": text,
                "timeout": timeout,
                "shell": shell,
            }
        )
        if call_index == self.fail_at:
            if self.fail_with_return:
                return CompletedProcess(
                    command,
                    7,
                    "hostile-return-stdout\n",
                    "hostile-return-stderr\n",
                )
            raise CalledProcessError(
                7,
                ["secret-command", "--token", "do-not-render"],
                output="hostile-failure-stdout\n",
                stderr="hostile-failure-stderr\n",
            )

        output_path = Path(command[-1])
        if call_index == 0:
            output_path.write_text(CORE_REQUIREMENTS, encoding="utf-8")
        elif call_index == 1:
            output_path.write_text(TUI_REQUIREMENTS, encoding="utf-8")
        elif call_index == 2:
            output_path.write_text(json.dumps(CORE_AUDIT), encoding="utf-8")
        elif call_index == 3:
            output_path.write_text(json.dumps(TUI_AUDIT), encoding="utf-8")
        else:
            raise AssertionError(f"unexpected fake command: {command}")
        if self.mutate_output is not None:
            self.mutate_output(call_index, output_path)
        if self.after_call is not None:
            self.after_call(call_index)
        return CompletedProcess(
            command,
            0,
            f"raw-stdout-{call_index}\n",
            f"raw-stderr-{call_index}\n",
        )


def _fixed_now() -> datetime:
    return FIXED_TIME


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _verify(tmp_path: Path, runner: RecordingRunner) -> tuple[tuple[Path, Path], Path]:
    evidence_dir = tmp_path / "dependency-audit"
    result_paths = verifier.verify_dependency_audit(
        evidence_dir,
        run_command=runner,
        now=_fixed_now,
    )
    return result_paths, evidence_dir.resolve()


def test_dependency_audit_verifier_exists() -> None:
    assert SCRIPT_PATH.is_file()


def test_build_commands_uses_exact_locked_core_and_tui_contract(tmp_path: Path) -> None:
    evidence_dir = tmp_path / "dependency-audit"
    core_path = evidence_dir / "core-requirements.txt"
    tui_path = evidence_dir / "tui-requirements.txt"
    core_output = evidence_dir / "core-pip-audit.json"
    tui_output = evidence_dir / "tui-pip-audit.json"

    assert verifier.build_commands(evidence_dir) == (
        (
            "uv",
            "export",
            "--frozen",
            "--no-dev",
            "--no-emit-project",
            "--format",
            "requirements.txt",
            "--output-file",
            str(core_path),
        ),
        (
            "uv",
            "export",
            "--frozen",
            "--no-dev",
            "--no-emit-project",
            "--extra",
            "tui",
            "--format",
            "requirements.txt",
            "--output-file",
            str(tui_path),
        ),
        (
            "uvx",
            "--from",
            "pip-audit==2.10.1",
            "pip-audit",
            "--requirement",
            str(core_path),
            "--no-deps",
            "--disable-pip",
            "--format",
            "json",
            "--output",
            str(core_output),
        ),
        (
            "uvx",
            "--from",
            "pip-audit==2.10.1",
            "pip-audit",
            "--requirement",
            str(tui_path),
            "--no-deps",
            "--disable-pip",
            "--format",
            "json",
            "--output",
            str(tui_output),
        ),
    )


def test_success_writes_validated_manifest_and_combined_raw_log(tmp_path: Path) -> None:
    runner = RecordingRunner()

    result_paths, evidence_dir = _verify(tmp_path, runner)

    assert result_paths == (
        evidence_dir / "core-pip-audit.json",
        evidence_dir / "tui-pip-audit.json",
    )
    manifest = json.loads((evidence_dir / "manifest.json").read_text(encoding="utf-8"))
    assert manifest == {
        "audit_tool": "pip-audit==2.10.1",
        "observed_at": "2026-07-15T12:34:56.123456+00:00",
        "paths": {
            "core": {
                "requirements": "core-requirements.txt",
                "result": "core-pip-audit.json",
            },
            "tui": {
                "requirements": "tui-requirements.txt",
                "result": "tui-pip-audit.json",
            },
        },
        "sha256": {
            "core-pip-audit.json": _sha256(evidence_dir / "core-pip-audit.json"),
            "core-requirements.txt": _sha256(evidence_dir / "core-requirements.txt"),
            "pip-audit.log": _sha256(evidence_dir / "pip-audit.log"),
            "tui-pip-audit.json": _sha256(evidence_dir / "tui-pip-audit.json"),
            "tui-requirements.txt": _sha256(evidence_dir / "tui-requirements.txt"),
            "uv.lock": _sha256(REPO_ROOT / "uv.lock"),
        },
    }
    combined_log = (evidence_dir / "pip-audit.log").read_text(encoding="utf-8")
    for call_index in range(4):
        assert f"raw-stdout-{call_index}\n" in combined_log
        assert f"raw-stderr-{call_index}\n" in combined_log
    assert not tuple(evidence_dir.glob(".*.tmp"))


def test_every_command_is_bounded_checked_sanitized_and_runs_at_repo_root(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("PIP_INDEX_URL", "https://token@hostile.invalid/simple")
    monkeypatch.setenv("UV_INDEX_URL", "https://token@hostile.invalid/simple")
    monkeypatch.setenv("PYTHONPATH", "/hostile/source")
    monkeypatch.setenv("VIRTUAL_ENV", "/hostile/venv")
    runner = RecordingRunner()

    _verify(tmp_path, runner)

    assert len(runner.calls) == 4
    for call in runner.calls:
        assert isinstance(call["args"], list)
        assert call["cwd"] == REPO_ROOT
        assert call["check"] is True
        assert call["capture_output"] is True
        assert call["text"] is True
        assert call["timeout"] == verifier.COMMAND_TIMEOUT_SECONDS
        assert call["shell"] is False
        environment = call["env"]
        assert "PIP_INDEX_URL" not in environment
        assert "UV_INDEX_URL" not in environment
        assert "PYTHONPATH" not in environment
        assert "VIRTUAL_ENV" not in environment
        assert environment["PIP_CONFIG_FILE"] == os.devnull
        assert environment["PIP_NO_INPUT"] == "1"
        assert environment["PYTHONNOUSERSITE"] == "1"
        assert environment["UV_NO_CONFIG"] == "1"


@pytest.mark.parametrize("fail_at", range(4))
def test_each_command_failure_stops_later_commands_and_cannot_emit_success(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
    fail_at: int,
) -> None:
    runner = RecordingRunner(fail_at=fail_at)
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(SystemExit) as excinfo:
        verifier.main(
            ["--evidence-dir", str(evidence_dir)],
            run_command=runner,
            now=_fixed_now,
        )

    captured = capsys.readouterr()
    assert excinfo.value.code == 2
    assert captured.out == ""
    assert len(runner.calls) == fail_at + 1
    assert not (evidence_dir / "manifest.json").exists()
    failure_log = (evidence_dir / "pip-audit.log").read_text(encoding="utf-8")
    assert "hostile-failure-stdout\n" in failure_log
    assert "hostile-failure-stderr\n" in failure_log
    assert "do-not-render" not in captured.err
    assert "hostile-failure" not in captured.err


def test_nonzero_return_is_fail_closed_even_when_runner_does_not_raise(tmp_path: Path) -> None:
    runner = RecordingRunner(fail_at=2, fail_with_return=True)
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match="exit status 7"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert len(runner.calls) == 3
    assert not (evidence_dir / "manifest.json").exists()
    failure_log = (evidence_dir / "pip-audit.log").read_text(encoding="utf-8")
    assert "hostile-return-stdout\n" in failure_log
    assert "hostile-return-stderr\n" in failure_log


def test_timeout_is_redacted_but_preserved_in_failure_log(tmp_path: Path) -> None:
    class TimeoutRunner(RecordingRunner):
        def __call__(self, *args: object, **kwargs: object) -> CompletedProcess[str]:
            if len(self.calls) == 2:
                self.calls.append({"args": list(args)})
                raise TimeoutExpired(
                    ["secret-command", "--token", "do-not-render"],
                    1,
                    output=b"timeout-secret-stdout\n",
                    stderr=b"timeout-secret-stderr\n",
                )
            return super().__call__(*args, **kwargs)

    runner = TimeoutRunner()
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError) as excinfo:
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert "timed out" in str(excinfo.value)
    assert "do-not-render" not in str(excinfo.value)
    assert "timeout-secret" not in str(excinfo.value)
    failure_log = (evidence_dir / "pip-audit.log").read_text(encoding="utf-8")
    assert "timeout-secret-stdout\n" in failure_log
    assert "timeout-secret-stderr\n" in failure_log
    assert not (evidence_dir / "manifest.json").exists()


def test_cli_prints_only_both_result_paths_after_complete_success(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    runner = RecordingRunner()
    evidence_dir = tmp_path / "dependency-audit"

    assert (
        verifier.main(
            ["--evidence-dir", str(evidence_dir)],
            run_command=runner,
            now=_fixed_now,
        )
        == 0
    )

    assert capsys.readouterr().out.splitlines() == [
        str(evidence_dir.resolve() / "core-pip-audit.json"),
        str(evidence_dir.resolve() / "tui-pip-audit.json"),
    ]


def test_existing_evidence_directory_is_rejected_before_any_command(tmp_path: Path) -> None:
    evidence_dir = tmp_path / "dependency-audit"
    evidence_dir.mkdir()
    runner = RecordingRunner()

    with pytest.raises(verifier.DependencyAuditError, match="must not already exist"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert runner.calls == []


def test_existing_file_at_evidence_path_is_rejected_before_any_command(tmp_path: Path) -> None:
    evidence_dir = tmp_path / "dependency-audit"
    evidence_dir.write_text("foreign", encoding="utf-8")
    runner = RecordingRunner()

    with pytest.raises(verifier.DependencyAuditError, match="must not already exist"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert runner.calls == []


def test_evidence_directory_symlink_is_rejected_before_any_command(tmp_path: Path) -> None:
    target = tmp_path / "target"
    target.mkdir()
    evidence_dir = tmp_path / "dependency-audit"
    evidence_dir.symlink_to(target, target_is_directory=True)
    runner = RecordingRunner()

    with pytest.raises(verifier.DependencyAuditError, match="must not be a symlink"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert runner.calls == []


def test_evidence_parent_symlink_is_rejected_before_any_command(tmp_path: Path) -> None:
    target = tmp_path / "target"
    target.mkdir()
    linked_parent = tmp_path / "linked-parent"
    linked_parent.symlink_to(target, target_is_directory=True)
    runner = RecordingRunner()

    with pytest.raises(verifier.DependencyAuditError, match="parent must not be a symlink"):
        verifier.verify_dependency_audit(
            linked_parent / "dependency-audit",
            run_command=runner,
            now=_fixed_now,
        )

    assert runner.calls == []


def test_missing_parent_directories_are_created_exclusively(tmp_path: Path) -> None:
    runner = RecordingRunner()
    evidence_dir = tmp_path / "new" / "nested" / "dependency-audit"

    verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert evidence_dir.is_dir()


@pytest.mark.parametrize("output_index", range(4))
def test_every_generated_output_must_be_a_regular_non_symlink_file(
    tmp_path: Path, output_index: int
) -> None:
    external = tmp_path / f"external-{output_index}"
    external.write_text("foreign", encoding="utf-8")

    def replace_with_symlink(call_index: int, output_path: Path) -> None:
        if call_index == output_index:
            output_path.unlink()
            output_path.symlink_to(external)

    runner = RecordingRunner(mutate_output=replace_with_symlink)
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match="regular non-symlink file"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert len(runner.calls) == output_index + 1
    assert not (evidence_dir / "manifest.json").exists()


@pytest.mark.parametrize("output_index", range(4))
def test_every_generated_output_must_be_nonempty(tmp_path: Path, output_index: int) -> None:
    def empty_output(call_index: int, output_path: Path) -> None:
        if call_index == output_index:
            output_path.write_bytes(b"")

    runner = RecordingRunner(mutate_output=empty_output)
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match="must not be empty"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert len(runner.calls) == output_index + 1
    assert not (evidence_dir / "manifest.json").exists()


@pytest.mark.parametrize("output_index", [0, 1])
def test_each_requirement_export_must_be_hash_locked(tmp_path: Path, output_index: int) -> None:
    def remove_hash(call_index: int, output_path: Path) -> None:
        if call_index == output_index:
            output_path.write_text("alpha==1.0\n", encoding="utf-8")

    runner = RecordingRunner(mutate_output=remove_hash)
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match="hash-locked"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert len(runner.calls) == output_index + 1
    assert not (evidence_dir / "manifest.json").exists()


@pytest.mark.parametrize("output_index", [2, 3])
def test_each_audit_output_must_be_valid_json(tmp_path: Path, output_index: int) -> None:
    def corrupt_json(call_index: int, output_path: Path) -> None:
        if call_index == output_index:
            output_path.write_text("not-json", encoding="utf-8")

    runner = RecordingRunner(mutate_output=corrupt_json)
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match="valid JSON"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert len(runner.calls) == output_index + 1
    assert not (evidence_dir / "manifest.json").exists()


@pytest.mark.parametrize("output_index", [2, 3])
def test_each_audit_output_must_report_no_vulnerabilities(
    tmp_path: Path, output_index: int
) -> None:
    def add_vulnerability(call_index: int, output_path: Path) -> None:
        if call_index == output_index:
            payload = CORE_AUDIT if output_index == 2 else TUI_AUDIT
            vulnerable = json.loads(json.dumps(payload))
            vulnerable["dependencies"][0]["vulns"] = [{"id": "GHSA-test"}]
            output_path.write_text(json.dumps(vulnerable), encoding="utf-8")

    runner = RecordingRunner(mutate_output=add_vulnerability)
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match="reported vulnerabilities"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert len(runner.calls) == output_index + 1
    assert not (evidence_dir / "manifest.json").exists()


def test_audit_dependency_set_must_match_the_hashed_requirements(tmp_path: Path) -> None:
    def omit_dependency(call_index: int, output_path: Path) -> None:
        if call_index == 3:
            output_path.write_text(json.dumps(CORE_AUDIT), encoding="utf-8")

    runner = RecordingRunner(mutate_output=omit_dependency)
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match="dependency set did not match"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert not (evidence_dir / "manifest.json").exists()


def test_earlier_output_mutation_is_detected_before_manifest(tmp_path: Path) -> None:
    evidence_dir = tmp_path / "dependency-audit"

    def mutate_core_after_final_command(call_index: int) -> None:
        if call_index == 3:
            (evidence_dir / "core-requirements.txt").write_text(
                "alpha==9.9 \\\n" + f"    --hash=sha256:{'9' * 64}\n",
                encoding="utf-8",
            )

    runner = RecordingRunner(after_call=mutate_core_after_final_command)

    with pytest.raises(verifier.DependencyAuditError, match="changed after validation"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert not (evidence_dir / "manifest.json").exists()


def test_foreign_manifest_cannot_be_replaced_with_success_evidence(tmp_path: Path) -> None:
    evidence_dir = tmp_path / "dependency-audit"

    def create_foreign_manifest(call_index: int) -> None:
        if call_index == 3:
            (evidence_dir / "manifest.json").write_text("foreign", encoding="utf-8")

    runner = RecordingRunner(after_call=create_foreign_manifest)

    with pytest.raises(verifier.DependencyAuditError, match="manifest already exists"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert (evidence_dir / "manifest.json").read_text(encoding="utf-8") == "foreign"


def test_missing_frozen_lock_is_rejected_before_any_command(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    fake_repo = tmp_path / "repo"
    fake_repo.mkdir()
    monkeypatch.setattr(verifier, "REPO_ROOT", fake_repo)
    runner = RecordingRunner()

    with pytest.raises(verifier.DependencyAuditError, match=r"uv\.lock"):
        verifier.verify_dependency_audit(
            tmp_path / "dependency-audit",
            run_command=runner,
            now=_fixed_now,
        )

    assert runner.calls == []


@pytest.mark.parametrize(
    ("payload", "message"),
    [
        (
            [{"name": "alpha", "version": "1.0", "vulns": []}],
            "JSON object",
        ),
        (
            {"dependencies": [{"name": "alpha", "version": "1.0", "vulns": []}]},
            "dependencies and fixes",
        ),
        (
            {
                "dependencies": [{"name": "alpha", "version": "1.0", "vulns": []}],
                "fixes": [],
                "unexpected": [],
            },
            "dependencies and fixes",
        ),
        (
            {
                "dependencies": [
                    {
                        "name": "alpha",
                        "version": "1.0",
                        "vulns": [],
                        "skip_reason": "package could not be audited",
                    }
                ],
                "fixes": [],
            },
            "skip reason",
        ),
        (
            {
                "dependencies": [
                    {"name": "alpha", "version": "1.0", "vulns": []},
                    {"name": "alpha", "version": "1.0", "vulns": []},
                ],
                "fixes": [],
            },
            "duplicate",
        ),
        (
            {"dependencies": [{"name": "alpha", "vulns": []}], "fixes": []},
            "version",
        ),
        (
            {
                "dependencies": [
                    {"name": "alpha", "version": "1.0", "vulns": [{"id": "CVE-test"}]}
                ],
                "fixes": [],
            },
            "vulnerabilities",
        ),
        (
            {
                "dependencies": [{"name": "alpha", "version": "1.0", "vulns": []}],
                "fixes": [{"name": "alpha", "version": "1.1"}],
            },
            "fixes",
        ),
    ],
)
def test_core_audit_requires_exact_pip_audit_json_object(
    tmp_path: Path,
    payload: object,
    message: str,
) -> None:
    def replace_core_audit(call_index: int, output_path: Path) -> None:
        if call_index == 2:
            output_path.write_text(json.dumps(payload), encoding="utf-8")

    runner = RecordingRunner(mutate_output=replace_core_audit)
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match=message):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert not (evidence_dir / "manifest.json").exists()


def test_empty_skip_reason_remains_valid_pip_audit_evidence(tmp_path: Path) -> None:
    def add_empty_skip_reason(call_index: int, output_path: Path) -> None:
        if call_index == 2:
            payload = json.loads(json.dumps(CORE_AUDIT))
            payload["dependencies"][0]["skip_reason"] = ""
            output_path.write_text(json.dumps(payload), encoding="utf-8")

    result_paths, evidence_dir = _verify(
        tmp_path,
        RecordingRunner(mutate_output=add_empty_skip_reason),
    )

    assert result_paths[0] == evidence_dir / "core-pip-audit.json"
    assert (evidence_dir / "manifest.json").is_file()


@pytest.mark.parametrize(
    "requirements_text",
    [
        "--index-url https://example.invalid/simple \\\n" + f"    --hash=sha256:{'d' * 64}\n",
        "alpha==1.0\n",
        _hashed_requirement("alpha>=1.0"),
        _hashed_requirement("alpha @ https://example.invalid/alpha-1.0.whl"),
        ("alpha==1.0 \\\n" + f"    --hash=sha256:{'e' * 64} \\\n" + f"    --hash=md5:{'f' * 32}\n"),
        _hashed_requirement("alpha==1.0") + _hashed_requirement("alpha==1.0"),
    ],
)
def test_requirements_reject_options_unlocked_urls_and_duplicates(
    tmp_path: Path,
    requirements_text: str,
) -> None:
    def replace_core_requirements(call_index: int, output_path: Path) -> None:
        if call_index == 0:
            output_path.write_text(requirements_text, encoding="utf-8")

    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match="requirements"):
        verifier.verify_dependency_audit(
            evidence_dir,
            run_command=RecordingRunner(mutate_output=replace_core_requirements),
            now=_fixed_now,
        )

    assert not (evidence_dir / "manifest.json").exists()


def test_active_marker_map_is_evaluated_for_current_platform_and_python_31211(
    tmp_path: Path,
) -> None:
    marker_requirements = _hashed_requirement(
        f'alpha==1.0 ; python_full_version == "3.12.11" and sys_platform == "{sys.platform}"',
        "1",
    ) + _hashed_requirement(
        'gamma==3.0 ; python_full_version < "3.12"',
        "3",
    )

    def replace_marker_evidence(call_index: int, output_path: Path) -> None:
        if call_index == 0:
            output_path.write_text(marker_requirements, encoding="utf-8")
        elif call_index == 2:
            output_path.write_text(
                json.dumps(
                    {
                        "dependencies": [{"name": "gamma", "version": "3.0", "vulns": []}],
                        "fixes": [],
                    }
                ),
                encoding="utf-8",
            )

    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match="active dependency map"):
        verifier.verify_dependency_audit(
            evidence_dir,
            run_command=RecordingRunner(mutate_output=replace_marker_evidence),
            now=_fixed_now,
        )

    assert not (evidence_dir / "manifest.json").exists()


def test_audit_version_must_exactly_match_active_pinned_requirement(tmp_path: Path) -> None:
    def replace_core_version(call_index: int, output_path: Path) -> None:
        if call_index == 2:
            output_path.write_text(
                json.dumps(
                    {
                        "dependencies": [{"name": "alpha", "version": "9.9", "vulns": []}],
                        "fixes": [],
                    }
                ),
                encoding="utf-8",
            )

    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match="active dependency map"):
        verifier.verify_dependency_audit(
            evidence_dir,
            run_command=RecordingRunner(mutate_output=replace_core_version),
            now=_fixed_now,
        )

    assert not (evidence_dir / "manifest.json").exists()


def test_multiple_active_versions_for_one_package_are_rejected(tmp_path: Path) -> None:
    ambiguous_requirements = _hashed_requirement(
        'alpha==1.0 ; python_version == "3.12"',
        "1",
    ) + _hashed_requirement(
        f'alpha==2.0 ; sys_platform == "{sys.platform}"',
        "2",
    )

    def replace_core_requirements(call_index: int, output_path: Path) -> None:
        if call_index == 0:
            output_path.write_text(ambiguous_requirements, encoding="utf-8")

    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match="multiple active versions"):
        verifier.verify_dependency_audit(
            evidence_dir,
            run_command=RecordingRunner(mutate_output=replace_core_requirements),
            now=_fixed_now,
        )

    assert not (evidence_dir / "manifest.json").exists()


def _write_fake_repo_lock(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> tuple[Path, Path]:
    repo_root = tmp_path / "repo"
    repo_root.mkdir()
    lockfile = repo_root / "uv.lock"
    lockfile.write_text("version = 1\nrevision = 1\n", encoding="utf-8")
    monkeypatch.setattr(verifier, "REPO_ROOT", repo_root)
    return repo_root, lockfile


def test_frozen_lock_must_not_be_a_hardlink(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    repo_root = tmp_path / "repo"
    repo_root.mkdir()
    original = tmp_path / "original.lock"
    original.write_text("version = 1\n", encoding="utf-8")
    os.link(original, repo_root / "uv.lock")
    monkeypatch.setattr(verifier, "REPO_ROOT", repo_root)
    runner = RecordingRunner()

    with pytest.raises(verifier.DependencyAuditError, match="single-link"):
        verifier.verify_dependency_audit(
            tmp_path / "dependency-audit",
            run_command=runner,
            now=_fixed_now,
        )

    assert runner.calls == []


@pytest.mark.parametrize("mutate_after", range(4))
def test_lock_mutation_after_each_command_stops_collection(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    mutate_after: int,
) -> None:
    _, lockfile = _write_fake_repo_lock(tmp_path, monkeypatch)

    def mutate_lock(call_index: int) -> None:
        if call_index == mutate_after:
            lockfile.write_text(
                f"version = 1\nrevision = {call_index + 2}\n",
                encoding="utf-8",
            )

    runner = RecordingRunner(after_call=mutate_lock)
    evidence_dir = tmp_path / "dependency-audit"

    with pytest.raises(verifier.DependencyAuditError, match=r"uv\.lock changed"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert len(runner.calls) == mutate_after + 1
    assert not (evidence_dir / "manifest.json").exists()


def test_clock_callback_mutation_precedes_final_digest_validation(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _write_fake_repo_lock(tmp_path, monkeypatch)
    evidence_dir = tmp_path / "dependency-audit"

    def mutating_now() -> datetime:
        (evidence_dir / "core-requirements.txt").write_text(
            CORE_REQUIREMENTS + "# mutated by clock\n",
            encoding="utf-8",
        )
        return FIXED_TIME

    with pytest.raises(verifier.DependencyAuditError, match="changed before publication"):
        verifier.verify_dependency_audit(
            evidence_dir,
            run_command=RecordingRunner(),
            now=mutating_now,
        )

    assert not (evidence_dir / "manifest.json").exists()


@pytest.mark.parametrize(
    "target_name",
    [
        "core-requirements.txt",
        "tui-requirements.txt",
        "core-pip-audit.json",
        "tui-pip-audit.json",
        "pip-audit.log",
        "uv.lock",
    ],
)
def test_direct_prepublication_mutation_cannot_publish_manifest(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    target_name: str,
) -> None:
    repo_root, lockfile = _write_fake_repo_lock(tmp_path, monkeypatch)
    evidence_dir = tmp_path / "dependency-audit"
    original_write_manifest = verifier._write_manifest

    def mutating_write_manifest(*args: object, **kwargs: object) -> None:
        target = lockfile if target_name == "uv.lock" else evidence_dir / target_name
        target.write_bytes(target.read_bytes() + b"\n")
        original_write_manifest(*args, **kwargs)

    monkeypatch.setattr(verifier, "_write_manifest", mutating_write_manifest)

    with pytest.raises(verifier.DependencyAuditError, match="changed before publication"):
        verifier.verify_dependency_audit(
            evidence_dir,
            run_command=RecordingRunner(),
            now=_fixed_now,
        )

    assert repo_root == verifier.REPO_ROOT
    assert not (evidence_dir / "manifest.json").exists()
    assert not tuple(evidence_dir.glob(".manifest.json.*.tmp"))


def test_each_run_uses_private_temporary_uv_cache_and_tool_directories(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    shared_cache = tmp_path / "shared-cache"
    shared_tools = tmp_path / "shared-tools"
    monkeypatch.setenv("UV_CACHE_DIR", str(shared_cache))
    monkeypatch.setenv("UV_TOOL_DIR", str(shared_tools))
    runner = RecordingRunner()

    _verify(tmp_path, runner)

    cache_values = {call["env"].get("UV_CACHE_DIR") for call in runner.calls}
    tool_values = {call["env"].get("UV_TOOL_DIR") for call in runner.calls}
    assert None not in cache_values
    assert None not in tool_values
    assert len(cache_values) == 1
    assert len(tool_values) == 1
    cache_dir = Path(cache_values.pop())
    tool_dir = Path(tool_values.pop())
    assert cache_dir != shared_cache
    assert tool_dir != shared_tools
    assert cache_dir.parent == tool_dir.parent
    assert not cache_dir.exists()
    assert not tool_dir.exists()


def test_evidence_leaf_creation_is_relative_to_a_held_parent_descriptor(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    if os.name != "posix":
        pytest.skip("descriptor-relative mkdir is POSIX-only")
    real_mkdir = verifier.os.mkdir
    mkdir_calls: list[tuple[str, int | None]] = []

    def recording_mkdir(
        path: str | bytes | os.PathLike[str] | os.PathLike[bytes],
        mode: int = 0o777,
        *,
        dir_fd: int | None = None,
    ) -> None:
        mkdir_calls.append((os.fsdecode(path), dir_fd))
        if dir_fd is None:
            real_mkdir(path, mode)
        else:
            real_mkdir(path, mode, dir_fd=dir_fd)

    monkeypatch.setattr(verifier.os, "mkdir", recording_mkdir)
    evidence_dir = tmp_path / "dependency-audit"

    verifier.verify_dependency_audit(
        evidence_dir,
        run_command=RecordingRunner(),
        now=_fixed_now,
    )

    assert any(path == evidence_dir.name and dir_fd is not None for path, dir_fd in mkdir_calls)


def test_generated_outputs_are_opened_relative_to_held_evidence_directory(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    if os.name != "posix":
        pytest.skip("descriptor-relative open is POSIX-only")
    real_open = verifier.os.open
    open_calls: list[tuple[str, int | None]] = []

    def recording_open(
        path: str | bytes | os.PathLike[str] | os.PathLike[bytes],
        flags: int,
        mode: int = 0o777,
        *,
        dir_fd: int | None = None,
    ) -> int:
        open_calls.append((os.fsdecode(path), dir_fd))
        if dir_fd is None:
            return real_open(path, flags, mode)
        return real_open(path, flags, mode, dir_fd=dir_fd)

    monkeypatch.setattr(verifier.os, "open", recording_open)
    evidence_dir = tmp_path / "dependency-audit"

    verifier.verify_dependency_audit(
        evidence_dir,
        run_command=RecordingRunner(),
        now=_fixed_now,
    )

    for filename in (
        "core-requirements.txt",
        "tui-requirements.txt",
        "core-pip-audit.json",
        "tui-pip-audit.json",
    ):
        assert any(path == filename and dir_fd is not None for path, dir_fd in open_calls)


def test_log_publication_renames_within_held_evidence_directory(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    if os.name != "posix":
        pytest.skip("descriptor-relative rename is POSIX-only")
    real_replace = verifier.os.replace
    replace_calls: list[tuple[str, str, int | None, int | None]] = []

    def recording_replace(
        source: str | bytes | os.PathLike[str] | os.PathLike[bytes],
        destination: str | bytes | os.PathLike[str] | os.PathLike[bytes],
        *,
        src_dir_fd: int | None = None,
        dst_dir_fd: int | None = None,
    ) -> None:
        replace_calls.append(
            (os.fsdecode(source), os.fsdecode(destination), src_dir_fd, dst_dir_fd)
        )
        if src_dir_fd is None and dst_dir_fd is None:
            real_replace(source, destination)
        else:
            real_replace(
                source,
                destination,
                src_dir_fd=src_dir_fd,
                dst_dir_fd=dst_dir_fd,
            )

    monkeypatch.setattr(verifier.os, "replace", recording_replace)

    _verify(tmp_path, RecordingRunner())

    assert any(
        destination == "pip-audit.log" and src_dir_fd is not None and src_dir_fd == dst_dir_fd
        for _, destination, src_dir_fd, dst_dir_fd in replace_calls
    )


def test_parent_swap_during_exclusive_leaf_creation_fails_closed(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    if os.name != "posix":
        pytest.skip("descriptor-relative creation race is POSIX-only")
    parent = tmp_path / "parent"
    parent.mkdir()
    moved_parent = tmp_path / "moved-parent"
    evidence_dir = parent / "dependency-audit"
    real_mkdir = verifier.os.mkdir
    did_swap = False

    def racing_mkdir(
        path: str | bytes | os.PathLike[str] | os.PathLike[bytes],
        mode: int = 0o777,
        *,
        dir_fd: int | None = None,
    ) -> None:
        nonlocal did_swap
        path_text = os.fsdecode(path)
        is_target = (dir_fd is None and Path(path_text) == evidence_dir) or (
            dir_fd is not None and path_text == evidence_dir.name
        )
        if is_target and not did_swap:
            parent.rename(moved_parent)
            real_mkdir(parent)
            did_swap = True
        if dir_fd is None:
            real_mkdir(path, mode)
        else:
            real_mkdir(path, mode, dir_fd=dir_fd)

    monkeypatch.setattr(verifier.os, "mkdir", racing_mkdir)
    runner = RecordingRunner()

    with pytest.raises(verifier.DependencyAuditError, match="changed during creation"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert did_swap is True
    assert runner.calls == []
    assert not (parent / "dependency-audit" / "manifest.json").exists()
    assert not (moved_parent / "dependency-audit" / "manifest.json").exists()


def test_evidence_leaf_swap_during_command_fails_without_external_success_evidence(
    tmp_path: Path,
) -> None:
    evidence_dir = tmp_path / "dependency-audit"
    moved_evidence = tmp_path / "moved-evidence"
    external = tmp_path / "external"
    external.mkdir()

    def swap_evidence_leaf(call_index: int) -> None:
        if call_index == 0:
            evidence_dir.rename(moved_evidence)
            evidence_dir.symlink_to(external, target_is_directory=True)

    runner = RecordingRunner(after_call=swap_evidence_leaf)

    with pytest.raises(verifier.DependencyAuditError, match="changed during collection"):
        verifier.verify_dependency_audit(evidence_dir, run_command=runner, now=_fixed_now)

    assert len(runner.calls) == 1
    assert not (external / "manifest.json").exists()
    assert not (moved_evidence / "manifest.json").exists()
